<a href="https://colab.research.google.com/github/kshitij-nandanwar/NNDL-Lab/blob/main/NNDL_Practical-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
vector1=np.array([10,20,30])
vector2=np.array([40,50,60])
print(vector1)
print(vector2)
result=vector1+vector2
print(result)

[10 20 30]
[40 50 60]
[50 70 90]


In [11]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[1,2],[3,4],[5,6]])
print('Matrix A')
print(vector1)
print()
print('Matrix B')
print(vector2)
result=np.matmul(A,B)
print()
print('Result')
print(result)

Matrix A
[[1 2 3]
 [4 5 6]]

Matrix B
[[1 2]
 [3 4]
 [5 6]]

Result
[[22 28]
 [49 64]]
